"""Added relations to sudoku registry

Revision ID: 3aca54698902
Revises: 7bda235d65a1
Create Date: 2025-01-02 22:38:30.277390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aca54698902'
down_revision: Union[str, None] = '7bda235d65a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sudoku_registry', 'sudoku', ['sudoku_id'], ['id'])
    op.create_foreign_key(None, 'sudoku_registry', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sudoku_registry', type_='foreignkey')
    op.drop_constraint(None, 'sudoku_registry', type_='foreignkey')
    # ### end Alembic commands ###
